<template id="ratings">
  <div>
    <div class="goods">
      <div class="menu-wrapper" ref="menuWrapper">
        <ul>
          <!--
            currentIndex Is generated by the computed attribute,
            determines whether index is equal to currentIndex,
            which is equal to the current class name
          -->
          <li
            class="menu-item"
            v-for="(item, index) in goods"
            :key="index"
            :class="{'current':currentIndex===index}"
            @click="selectMenu(index, $event)"
          >
            <span class="text border-1px">
              <span
                v-show="item.type>0"
                class="icon"
                :class="classMap[item.type]"
              >
              </span>{{item.name}}
            </span>
          </li>
        </ul>
      </div>
      <div class="foods-wrapper" ref="foodsWrapper">
        <ul>
          <li
            class="food-list food-list-hook"
            v-for="(item, index) in goods"
            :key="index"
          >
            <h1 class="title">{{item.name}}</h1>
            <ul>
              <li
                class="food-item border-1px"
                v-for="(food, index) in item.foods"
                :key="index"
                @click="selectFood(food, $event)"
              >
                <div class="icon">
                  <img width="57" height="57" :src="food.icon"/>
                </div>
                <div class="content">
                  <h2 class="name">{{food.name}}</h2>
                  <p class="desc">{{food.description}}</p>
                  <div class="extra">
                    <span class="count">月售{{food.sellCount}}份</span><span>好评率{{food.rating}}%</span>
                  </div>
                  <div class="price">
                    <span class="now">￥{{food.price}}</span>
                    <span class="old" v-show="food.oldPrice">￥{{food.oldPrice}}</span>
                  </div>
                  <div class="cartControl-wrapper">
                    <cartControl :food="food" @add="addFood"></cartControl>
                  </div>
                </div>
              </li>
            </ul>
          </li>
        </ul>
      </div>
      <shopCart
        ref="shopCart"
        :selectFoods="selectFoods"
        :deliveryPrice="seller.deliveryPrice"
        :minPrice="seller.minPrice"
      >
      </shopCart>
    </div>
    <food ref="food" :food="selectedFood" @add="addFood"></food>
  </div>
</template>

<script type="text/ecmascript-6">
import BScroll from 'better-scroll'
import shopCart from '../shopCart/shopCart.vue'
import cartControl from '../cartControl/cartControl.vue'
import food from '../food/food.vue'

const ERR_OK = 0

export default {
	components: {
		shopCart,
		food,
		cartControl
	},
	/* accpet App.vue pass seller */
	props: {
		seller: {
			type: Object
		}
	},
	data() {
		return {
			goods: [],
			/* an array of heights for each dish */
			listHeight: [],
			/* foodsScroll rolling position */
			scrollY: 0,
			selectedFood: {}
		}
	},
	computed: {
		currentIndex() {
			for (let i = 0; i < this.listHeight.length; i++) {
				/* 当前索引值的高度 */
				let height1 = this.listHeight[i]
				/* 下一个的高度 */
        let height2 = this.listHeight[i + 1]
				if (!height2 || (this.scrollY >= height1 && this.scrollY < height2)) {
					return i
				}
			}
			return 0
		},
		/* 所有单独的菜肴的集合. */
		selectFoods() {
			let foods = []
			/* http://localhost:8088/api/goods */ 
			/* good -> 左侧栏的单个项目 */
			this.goods.forEach(good => {
				/* food -> 项目中的单个菜品. */
				good.foods.forEach(food => {
          /* food.count: cartcontrol.vue setting */
					if (food.count) {
						foods.push(food)
					}
				})
			})
			return foods
		}
	},
	created() {
		this.classMap = ['decrease', 'discount', 'special', 'invoice', 'guarantee']
		this.$http.get('/api/goods').then(response => {
			// console.log(response)
			/* get json object */
			response = response.body
			if (response.errno === ERR_OK) {
				this.goods = response.data
				/*
        async
        在下次 DOM 更新循环结束之后执行延迟回调。
        在修改数据之后立即使用这个方法，获取更新后的 DOM。
        */
				this.$nextTick(() => {
					this._initScroll()
					this._calculateHeight()
				})
			}
		})
	},
	methods: {
		_initScroll() {
			this.meunScroll = new BScroll(this.$refs.menuWrapper, {
				click: true
			})
			this.foodsScroll = new BScroll(this.$refs.foodsWrapper, {
				click: true,
        /*
        probeType: 1，会非实时（屏幕滑动超过一定时间后）派发scroll 事件
        probeType: 2，会在屏幕滑动的过程中实时的派发 scroll 事件
        probeType: 3，不仅在屏幕滑动的过程中，而且在 momentum 滚动动画运行过程中实时派发 scroll 事件(实时滚动位置)
        */
				probeType: 3
			})
			this.foodsScroll.on('scroll', pos => {
				/* scrollY: foodsScroll 滚动位置(实时滚动位置) */
				this.scrollY = Math.abs(Math.round(pos.y))
			})
		},
		_calculateHeight() {
			let foodList = this.$refs.foodsWrapper.getElementsByClassName('food-list-hook')
			let height = 0
			/* listHeight: 每道菜的高度排列 */
			this.listHeight.push(height)
			for (let i = 0; i < foodList.length; i++) {
				let item = foodList[i]
        /* clientHeight: static/clientHeight.png */
        /*
        width: 样式宽
      	clientWidth: 可视区宽 = 样式宽 + padding
      	offsetWidth: 占位宽 = 样式宽 + padding + border
        */
				height += item.clientHeight
				this.listHeight.push(height)
			}
		},
		selectMenu(index, event) {
      /* better-scroll */
      /* 在 PC 将触发两次事件，停止这个 */
			if (!event._constructed) {
				return
			}
			let foodList = this.$refs.foodsWrapper.getElementsByClassName('food-list-hook')
			let el = foodList[index]
			/* target: element, duration: 300ms */
			this.foodsScroll.scrollToElement(el, 300)
		},
		selectFood(food, event) {
      /* better-scroll */
      /* at PC will trigger twice event, stop this */
			if (!event._constructed) {
				return
			}
			this.selectedFood = food
			this.$refs.food.show()
		},
		addFood(target) {
			this._drop(target)
		},
		_drop(target) {
      /*
      异步执行抛物小球动画，缓解卡顿
      在下次 DOM 更新循环结束之后执行延迟回调。
      在修改数据之后立即使用这个方法，获取更新后的 DOM。
      */
			this.$nextTick(() => {
				this.$refs.shopCart.drop(target)
			})
		}
	}
}
</script>

<style rel="stylesheet/scss" lang="scss">
@import 'goods.scss';
</style>
